Added support for loading CSV with WGS84
RobotecAI/robotec-o3de-tools pull request #23
Opened 2024-05-24 14:18 UTC by michalpelka

Added way to import WGS84. 
Omitted using o3de asset for handling filenames of CSV.

2024-05-27 08:04 UTC, zakmat commented
Interesting addition. The biggest issue I see is that the change introduces a dependency on a development branch of ROS2 Gem. I won't be able to use this Gem in projects that are based on released ROS2 Gems

2024-05-27 08:28 UTC, michalpelka commented
Thanks @zakmat. 
This repo is not canonical to o3de. It serves the community as coding examples. In other words, if someone has a need to use a CSV importer to splines, one can use the last code https://github.com/RobotecAI/robotec-o3de-tools/commit/dc7376de73575583045e1a47262bbfa87629d52a.
We can also change the ROS 2 repo from o3de-extras and split georeference into separate Gem.

2024-08-08 13:17 UTC, pijaro commented on Gems/RobotecSplineTools/Code/Source/Tools/SplineToolsEditorComponent.cpp
> +            const bool isCoordinateLatLon = !(index_Lat < 0 || index_Lon < 0 || index_Alt < 0);
Unnecessary new variable? Why don't you use `m_isLatLonAlt`?

2024-08-08 13:17 UTC, pijaro commented on Gems/RobotecSplineTools/Code/Source/Tools/SplineToolsEditorComponent.cpp
> +                    // handle Z column
Nitpick, unnecessary comment.
```suggestion
```

2024-08-08 13:17 UTC, pijaro commented on Gems/RobotecSplineTools/Code/Source/Tools/SplineToolsEditorComponent.cpp
> +            const int index_Alt = reader.index_of("alt");
Naming convention?

```
index_Lat -> indexLat
index_Lon -> indexLon
index_Alt -> indexAlt
```

2024-09-30 08:54 UTC, pijaro requested changes
Can we also update the readme?

2024-09-30 14:27 UTC, michalpelka commented
@pijaro  added.

2024-10-01 07:55 UTC, pijaro approved these changes

2024-10-01 14:00 UTC, merged