Wc/snap to terrain - CsvSpawner: Make "snap to terrain" based on collision layer.
RobotecAI/robotec-o3de-tools pull request #74
Opened 2024-10-10 11:41 UTC by wc-robotec

I've added CollisionLayer to AssetConfig.
When Place On Terrain is Enabled - then a layer can be chosen to which object will be attached on spawn.
![Screenshot from 2024-10-10 13-05-47](https://github.com/user-attachments/assets/243e060a-598f-41f2-a4fe-f26355bf8a06)
![Screenshot from 2024-10-10 13-01-01](https://github.com/user-attachments/assets/b83730c4-ead6-4d27-8c1b-a02a4d9e96df)

2024-10-10 13:49 UTC, pijaro requested changes
Please fix the namespaces and formatting. Also, some changes look like reverting to the older version (most probably because you were using the older snapshot when working on it).

2024-10-10 13:49 UTC, pijaro commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.h
> +        AZ_RTTI(CsvSpawnableEntityInfo, "{6acce47e-9cac-4a6e-8726-ea614fb2d30d}");
Keep the previous style of keeping the type id

2024-10-10 13:49 UTC, pijaro commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.h
> +        AZ_RTTI(CsvSpawnableAssetConfiguration, "{d04ea4de-b4dc-4e76-b742-c1d77203bc3e}");
Keep the previous style of keeping the type id

2024-10-10 13:49 UTC, pijaro commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.h
> +namespace RobotecEnvironmentSpawner::CsvSpawnerUtils
Wrong namespace.

2024-10-10 13:49 UTC, pijaro commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.h
> +}; // namespace RobotecEnvironmentSpawner::CsvSpawnerUtils
Wrong namespace.

2024-10-10 13:49 UTC, pijaro commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.cpp
> +            optionalArgs.m_completionCallback = [parentId]([[maybe_unused]] AzFramework::EntitySpawnTicket::Id ticketId, AzFramework::SpawnableConstEntityContainerView view)
Formatting

2024-10-10 14:52 UTC, wc-robotec commented
I've copied the code from version I had in Kubota repo. 
Reverted changes and applied only pieces of code I've changed.

2024-10-10 14:58 UTC, wc-robotec reviewed
Updated

2024-10-17 15:45 UTC, michalpelka commented on Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.cpp
> +        if (sceneHandle == AzPhysics::InvalidSceneHandle)
```suggestion
        AZ_Assert(sceneHandle == AzPhysics::InvalidSceneHandle, "Unable to get  scene handle");
        if (sceneHandle == AzPhysics::InvalidSceneHandle)
```

2024-10-17 15:54 UTC, michalpelka requested changes
Code is not fromated:
![image](https://github.com/user-attachments/assets/2a9a2330-9788-41ac-a22b-d8e7610a08db)
And there is a problem with missing headers
/home/michalpelka/github/ROSConDemo2023WorkDir/robotec-o3de-tools/Gems/CsvSpawner/Code/Source/CsvSpawner/CsvSpawnerUtils.h:63:3: error: use of undeclared identifier 'AzPhysics'
                AzPhysics::CollisionLayer m_selectedCollisionLayer; //!< To which collision layer this target will be attached

2024-10-17 16:03 UTC, michalpelka commented
Please fix compilation error:
https://gist.github.com/michalpelka/6ff222566d2a56527dc6852c13d818b4

2024-10-18 14:15 UTC, wc-robotec commented
Fixed missing header error and added Az_Asert.
Also applied clang format - which fails ?
Could you please check if it's correctly formatted?

2024-10-28 14:51 UTC, michalpelka requested changes
Formatting was changed to other than o3de default. Please revert it

2024-10-28 15:48 UTC, michalpelka approved these changes

2024-11-12 12:54 UTC, pijaro approved these changes

2024-11-12 12:55 UTC, merged