Watchdog rule for required components verification.
RobotecAI/robotec-o3de-tools pull request #87
Opened 2024-11-20 07:47 UTC by lawendah

This PR adds a rule, which allows to check if all components listed in setreg file are present in runtime. It extends (with small adjustments) current API.

2025-03-17 13:44 UTC, michalpelka approved these changes

2025-05-05 10:17 UTC, michalpelka approved these changes

2025-07-25 09:30 UTC, jhanca-robotecai requested changes
When changing anything in Gem, please bump _version_ number in `gem.json`.

Do we need to cherry-pick this PR to 2505 as well?

2025-07-25 10:06 UTC, jhanca-robotecai commented
Closing without merging after the internal discussion.

2025-07-25 10:06 UTC, closed without merging